/controller_manager:
  ros__parameters:
    update_rate: 250
    use_sim_time: true

    joint_state_broadcaster.type: joint_state_broadcaster/JointStateBroadcaster
    arm_left_controller.type: joint_trajectory_controller/JointTrajectoryController
    arm_right_controller.type: joint_trajectory_controller/JointTrajectoryController
    head_controller.type: joint_trajectory_controller/JointTrajectoryController
    torso_controller.type: joint_trajectory_controller/JointTrajectoryController
    gripper_left_controller_raw.type: joint_trajectory_controller/JointTrajectoryController
    gripper_right_controller_raw.type: joint_trajectory_controller/JointTrajectoryController
